name: 15. Workflow filter and activity type
on:
  push:
    branches: ['!feature', main]
  pull_request:
    branches:
      - main
      - development
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - 'src/**'                    # Trigger only when change in src and its sub directories.
jobs:
  if-expression:
    name: workflow filter and activity type
    runs-on: ubuntu-latest
    steps:
      - name: github context
        if: github.repository_owner == 'meeran2019'
        run: |
          echo "The github context is:"
          echo "${{ toJson(github) }}"
          echo ""
          echo "The github context is:"
          echo "${{ toJson(github.repositoryUrl) }}"
          echo ""          