name: 17. Caching
on: 
  push:
  workflow_dispatch: 
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:                                      
            - name: welcome message
              run: |
                echo "my first workflow" > test.txt
                ls -ltr
            - name: cache
              uses: actions/cache@v4
              with:
                path: test.txt
                key: cache-test
    second-job:
        runs-on: ubuntu-latest
        needs: first-job
        steps:                                      
            - name: restore cache
              uses: actions/cache@v4
              with:
                path: test.txt
                key: cache-test                
            - name: read cache
              run: |
                ls -ltr
    third-job:
        runs-on: ubuntu-latest
        needs: second-job
        steps:                                      
            - name: save cache
              uses: actions/cache@v4
              id: cache-test-1
              with:
                path: test.txt
                key: cache-test                
            - name: read cache
              run: |
                ls -ltr                