## This is second example on github actions.
## Here focussed on multi line run commands

name: multi line workflow
on: push
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4             #It download the FULL repository. 
            - name: welcome message
              run: | 
                echo "my first workflow"
                echo "my second message"
                cat notes 