## This is second example on github actions.
## Here focussed on multi line run commands

name: 2. multi line run workflow
on: push
jobs:
    multiline-job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4             # It download the FULL repository. 
            - name: welcome message
              run: |                                # pipe symbol used to run the multiple commands.
                echo "my first workflow"
                echo "my second message"
                cat notes 