# Underlying host runs on runner and call by localhost:port for testing.

name: 20. Service Container
on:
  push:
jobs:  
  service-container:
    runs-on: ubuntu-latest
    services:                           # Since no container property, it runs on ubuntu-latest server. 
      redis:                            
        image: redis 
        options: 
          -- name redis                 # To define label. 
        ports:
          - 6379:6379
    steps:
    - uses: actions/checkout@main
    - name: run ls
      run: ls