# Both job and service runs as container and share same network and call from job container to service container by using service label.

name: 21. Job Service Container
on:
  push:
jobs:  
  job-service-container:
    runs-on: ubuntu-latest
    container:                          # Primary job is running on container with this image. This is Docker host.  
      image: ubuntu:latest
    services:                           # It also call another service container while execution. 
      redis:                            # Service LABEL.
        image: redis 
        ports:
          - 6379:6379
    steps:
    - uses: actions/checkout@main
    - name: run ls
      run: ls