
name: 22. GITHUB_ENV file for Environment variabe.
on: 
  workflow_dispatch:
  push:
jobs:              
    first-job:
        runs-on: ubuntu-latest                            
        steps:
            - name: run first job first step    
              run: |                              # NOTE: - (hyphen) cannot work and use underscore.              
                echo "dynamic_env_key=test_value" >> "$GITHUB_ENV"      
            - name: run first job second step.
              run: |                              # Below are the 2 ways to retrive the values.
                echo value from step 1 dynamic variable is $dynamic_env_key
                echo value from step 1 dynamic variable using env is  ${{ env.dynamic_env_key }}
    second-job:
        runs-on: ubuntu-latest           
        needs: first-job                 
        steps:
            - name: to test whether GITHUB_ENV is population another job or not.
              run: |                                          ## It is tested and not populated in another job.
                echo value from step 1 dynamic variable is $dynamic_env_key
