name: 24. environment
on: 
  workflow_dispatch:
  push:
jobs:
  dev-environment-job:
    environment: 
      name: develop
      url: https://dev-url.coms
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |                            # Since environment is develop, it wont fetch prod environment secrets.
          echo "test"
          echo Environment level ENV_DEV_KEY1 ${{ secrets.ENV_DEV_KEY1 }}
          echo Environment level ENV_DEV_VAR_KEY1 ${{ vars.ENV_DEV_VAR_KEY1 }}
          echo Repo level MY_SECRET_VALUE1 ${{ secrets.MY_SECRET_VALUE1 }}
          echo Repo level MY_VARIABLE1 ${{ vars.MY_VARIABLE1 }}
          echo Prod Environment secret ${{ secrets.PROD_SECRET }}

  prod-environment-job:
    environment: 
      name: production
      url: https://prod-url.com
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |                      # In below, develop environment cant fetch since production environment defined. It display repo level secrets/variables.
          echo "test"
          echo Environment level ENV_DEV_KEY1 ${{ secrets.ENV_DEV_KEY1 }}
          echo Environment level ENV_DEV_VAR_KEY1 ${{ vars.ENV_DEV_VAR_KEY1 }}
          echo Repo level MY_SECRET_VALUE1 ${{ secrets.MY_SECRET_VALUE1 }}
          echo Repo level MY_VARIABLE1 ${{ vars.MY_VARIABLE1 }}
          echo Prod Environment secret ${{ secrets.PROD_SECRET }}
