name: 26. Reusable or called workflow.
on: 
  workflow_call: 
    secrets:                                          ## To get the secret from caller workflow. 
      aws_pwd:
        description: enter the pwd
        required: true
    inputs:                                           ## To get env variable from caller workflow.
      region:
        required: true
        type: string        
jobs:
  called-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |                                        ## To refer the secret in called workflow.
          echo aws_pwd is ${{ secrets.aws_pwd }}
          echo region is ${{ inputs.region }}