name: 26. Reusable or called workflow.
on: 
  workflow_call: 
    secrets:
      aws_pwd:
        description: enter the pwd
        required: true
jobs:
  called-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: | 
          echo aws_pwd is $aws_pwd