name: 26. Reusable or called workflow.
on: 
  workflow_call: 
    inputs:
      region:
        required: true
        type: string
    secrets:
      aws_pwd:
        description: enter the pwd
        required: true
jobs:
  called-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.aws_pwd }}
          configuration-path: ${{ inputs.region }}
      - name: display output
        run: | 
          echo repo-token is ${repo-token}
          echo configuration-path is ${configuration-path}
