name: 26. Reusable or called workflow.
on: 
  workflow_call: 
    inputs:
      region:
        required: false
        type: string
    secrets:
      aws_pwd:
        description: enter the pwd
        required: false
jobs:
  called-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1          
        run: |                    
          echo "test"
