name: 27. Caller workflow
on: 
  push: 
  workflow_dispatch: 
jobs:
  caller-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1          
        uses: ./.github/workflows/26.reusable-called-wf.yaml

