name: 27. Caller workflow
on: 
  push: 
  workflow_dispatch: 
jobs:
  caller-job:
    uses: ./.github/workflows/26.reusable-called-wf.yaml
    with:
      region: .github/labeler.yml
    secrets:
      aws_pwd: ${{ secrets.GITHUB_TOKEN }}

        

