name: 27. Caller workflow for secrets and inputs (env var).
on: 
  push: 
  workflow_dispatch: 
jobs:
  caller-job:
    uses: ./.github/workflows/26.reusable-called-wf.yaml
    secrets:
      aws_pwd: ${{ secrets.GITHUB_TOKEN }}
    with:
      region: us-east-1

        

