name: 29. Caller workflow for outputs.
on: 
  push: 
  workflow_dispatch: 
jobs:
  caller-job:
    uses: ./.github/workflows/28.reusable-called-wf-output.yaml
  caller-job-2:
    runs-on: ubuntu-latest
    needs: caller-job
    steps:
      - name: job2 step1
        run: | 
          echo ${{ needs.caller-job.outputs.from_reusable_wf_1 }}
          echo ${{ needs.caller-job.outputs.from_reusable_wf_2 }}
        

