## This is third example on github actions.
## Here focussed on running multiple commands.

name: 3. execute multiple commands workflow
on: push
jobs:
    execute-command-job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4             # It download the FULL repository. 
            - name: welcome message
              run: |                                # pipe symbol used to run the multiple commands.
                echo "my first workflow"
                sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
                curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
                sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
                sudo apt-get update && sudo apt-get install terraform
                terraform -v