## This is fifth example on github actions.
## Here focussed on running multiple jobs..

name: 5. running multiple jobs
on: push
jobs:
    first-job:                                            # This is first job.
        runs-on: ubuntu-latest
        steps:
            - name: run first job first step
              run: echo "run first job first step"
    second-job:
        needs: first-job                                  # By default, 2nd job run parallel and separate machine.
        runs-on: ubuntu-latest                            # needs which is used to add dependency. 
        steps:
            - name: run second job first step
              run: echo "run second job first step"              
    third-job:
        runs-on: ubuntu-latest
        steps:
            - name: run third job first step
              run: echo "run third job first step"