## This is sixth example on github actions..
## Here focussed on to pass artifacts from one job to another.

name: 6. to pass artifacts from one job to another.
on: 
  workflow_dispatch:
  push:
jobs:
    first-job:                                            # This is first job.
        runs-on: ubuntu-latest
        steps:
            - name: run first job first step
              run: echo "run first job first step"
            - name: create a test file
              run: |                                      # create a directory otherwise fails to download.
                 mkdir test-folder
                 cd test-folder
                 touch test.txt
            - name: upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: artifact-name1
                path: test-folder
    second-job:
        needs: first-job                                  # By default, 2nd job run parallel and separate machine.
        runs-on: ubuntu-latest                            # needs which is used to add dependency. 
        steps:
            - name: run second job first step
              run: echo "run second job first step"
            - name: download artifact which passed in first job.
              uses: actions/download-artifact@v4
              with:
                name: artifact-name1
                path: test-folder
                retention: 5                              # can give retention in days for available.
            - name: to read the artifact file from first job.     
              run: |                                      # give the full path to download directory.
                cat test-folder/test.txt