## This is seventh example on github actions.
## Here focussed on environment variables.

name: 7. environment variables.
on: 
  workflow_dispatch:
  push:
jobs:
    first-job:                                            # This is first job.
        runs-on: ubuntu-latest
        steps:
            - name: run first job first step
              run: echo "run first job first step"
            - name: create a test file
              run: touch test.txt
            - name: upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: artifact-name1
                path: test.txt              
    second-job:
        needs: first-job                                  # By default, 2nd job run parallel and separate machine.
        runs-on: ubuntu-latest                            # needs which is used to add dependency. 
        steps:
            - name: run second job first step
              env:                                        # to define env variable at step level.
                ENV_COLOR: blue
                ENV_BIRD: sparrow
              run: |
                echo "color is $ENV_COLOR"
                echo "color is ${ENV_COLOR}"
                echo bird is $ENV_BIRD
                echo bird is ${ENV_BIRD}