## This is seventh example on github actions.
## Here focussed on environment variables.

name: 7. environment variables.
on: 
  workflow_dispatch:
  push:
env:
  WORKFLOW_LEVEL_KEY1: workflow-value1
  WORKFLOW_LEVEL_KEY2: workflow-value-2
jobs:              
    first-job:
        env:
          JOB_LEVEL_KEY1: job-value1
          JOB_LEVEL_KEY2: job-value2
          WORKFLOW_LEVEL_KEY2: workflow-value-xxxx        # override the workflow one.
        runs-on: ubuntu-latest                            # needs which is used to add dependency. 
        steps:
            - name: run first job first step
              env:                                        # to define env variable at step level.
                ENV_COLOR: blue
                ENV_BIRD: sparrow
                JOB_LEVEL_KEY1: job-valuexxx              # override at step level.
                WORKFLOW_LEVEL_KEY2: workflow-value-yyyy
              run: |                                      # first 4 combinations are working. ${} must use along with suffix or prefix
                echo WORKFLOW_LEVEL_KEY2 is $WORKFLOW_LEVEL_KEY2
                echo JOB_LEVEL_KEY1 is $JOB_LEVEL_KEY1
                echo "color is $ENV_COLOR"                
                echo "color is ${ENV_COLOR}"
                echo bird is $ENV_BIRD
                echo bird is ${ENV_BIRD}
                echo "color is $ENV_COLOR_test"                
                echo "color is ${ENV_COLOR}_test"
                echo bird is $ENV_BIRD_test
                echo bird is ${ENV_BIRD}_test                
            - name: run first job second step.
              run: | 
                echo color is $ENV_COLOR
                echo job level is $JOB_LEVEL_KEY1
                echo workflow level is $WORKFLOW_LEVEL_KEY1