## This is eighth example on github actions.
## Here focussed on repository level secret and variables.

name: 8. repository secrets and variables.
on: 
  workflow_dispatch:
  push:
jobs:              
    first-job:
        runs-on: ubuntu-latest                            
        steps:
            - name: run first job first step
              run: |                                      
                echo MY_SECRET_VALUE1 is $MY_SECRET_VALUE1
                echo MY_VARIABLE1 is $MY_VARIABLE1
                echo MY_SECRET_VALUE1 is ${{ secrets.MY_SECRET_VALUE1 }}
                echo MY_VARIABLE1 is ${{ vars.MY_VARIABLE1 }}              