## This is eighth example on github actions.
## Here focussed on repository level secret and variables.

name: 8. repository secrets and variables.
on: 
  workflow_dispatch:
  push:
jobs:              
    first-job:
        runs-on: develop
        steps:
            - name: run first job first step
              run: |                                      
                echo MY_SECRET_VALUE1 is ${{ secrets.MY_SECRET_VALUE1 }}
                echo MY_VARIABLE1 is ${{ vars.MY_VARIABLE1 }}              
                echo ENV_DEV_KEY1 is ${{ secrets.ENV_DEV_KEY1 }}
                echo ENV_DEV_VAR_KEY1 is ${{ vars.ENV_DEV_VAR_KEY1 }}