name: my first workflow
on: push
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: welcome message
              run: echo "my first workflow"
            - name: second message
              run: echo "my second message"
            - name: read notes 
              run: cat README.md


